export const topRecipesList = [
    {
        id: 1,
        type: ['Pizza', 'Pizza'],
        name: 'The Chicken King',
        time: 24,
        rating: 4.8,
        image: '/images/recipes-1.png',
    },
    {
        id: 2,
        type: ['Pizza'],
        name: 'The Burger King',
        time: 24,
        rating: 4.9,
        image: '/images/recipes-2.png',
    },
    {
        id: 3,
        type: ['Pizza'],
        name: 'The Chicken King',
        time: 24,
        rating: 4.8,
        image: '/images/recipes-1.png',
    },
    {
        id: 4,
        type: ['Pizza'],
        name: 'The Chicken King',
        time: 24,
        rating: 4.8,
        image: '/images/recipes-1.png',
    },
    {
        id: 5,
        type: ['Pizza'],
        name: 'The Burger King',
        time: 24,
        rating: 4.9,
        image: '/images/recipes-2.png',
    },
    {
        id: 6,
        type: ['Pizza'],
        name: 'The Chicken King',
        time: 24,
        rating: 4.8,
        image: '/images/recipes-1.png',
    },
]
