export const user = {
    id: 9,
    firstName: 'Demetrius',
    lastName: 'Corkery',
    maidenName: 'Gleason',
    age: 22,
    gender: 'male',
    email: 'nloiterton8@aol.com',
    phone: '+86 356 590 9727',
    username: 'nloiterton8',
    password: 'HTQxxXV9Bq4',
    birthDate: '1971-03-11',
    image: 'https://robohash.org/Demetrius.png?set=set4',
    bloodGroup: 'A+',
    height: 170,
    weight: 97.1,
    eyeColor: 'Green',
    hair: { color: 'Brown', type: 'Strands' },
    domain: 'goodreads.com',
    ip: '78.170.185.120',
    address: {
        address: '5403 Illinois Avenue',
        city: 'Nashville',
        coordinates: { lat: 36.157077, lng: -86.853827 },
        postalCode: '37209',
        state: 'TN',
    },
    macAddress: '98:EE:94:A2:91:C4',
    university: 'Nanjing University of Economics',
    bank: {
        cardExpire: '02/24',
        cardNumber: '5372664789004621',
        cardType: 'mastercard',
        currency: 'Yuan Renminbi',
        iban: 'BR68 9829 0581 3669 5088 5533 025N V',
    },
    company: {
        address: {
            address: '12245 West 71st Place',
            city: 'Arvada',
            coordinates: { lat: 39.8267078, lng: -105.1366798 },
            postalCode: '80004',
            state: 'CO',
        },
        department: 'Human Resources',
        name: 'Gorczany Group',
        title: 'Community Outreach Specialist',
    },
    ein: '14-1066382',
    ssn: '717-26-3759',
    userAgent:
        'Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_4_11; de) AppleWebKit/528.4+ (KHTML, like Gecko) Version/4.0dp1 Safari/526.11.2',
    crypto: {
        coin: 'Bitcoin',
        wallet: '0xb9fc4b4b855bc44eb30d5e36fd18f491f44a15b7',
        network: 'Ethereum (ERC20)',
    },
}
export const post = {
    id: 9,
    title: 'There are different types of secrets.',
    body: "There are different types of secrets. She had held onto plenty of them during her life, but this one was different. She found herself holding onto the worst type. It was the type of secret that could gnaw away at your insides if you didn't tell someone about it, but it could end up getting you killed if you did.",
    userId: 42,
    tags: ['american', 'history', 'magical'],
    reactions: 2,
}
export const comments = {
    comments: [
        {
            id: 76,
            body: 'This really sparkles!',
            postId: 9,
            user: { id: 17, username: 'vcholdcroftg' },
        },
        {
            id: 146,
            body: 'You’ve got a beautiful heart.',
            postId: 9,
            user: { id: 23, username: 'beykelhofm' },
        },
        {
            id: 259,
            body: 'This looks exotic.',
            postId: 9,
            user: { id: 90, username: 'omottley2h' },
        },
        {
            id: 321,
            body: 'You’re really getting good at these trending Instagram challenges, I must say.',
            postId: 9,
            user: { id: 85, username: 'kpondjones2c' },
        },
    ],
    total: 4,
    skip: 0,
    limit: 4,
}
